<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->get('/', 'Homepage::index');
$routes->get('welcome', 'Homepage::index');
$routes->get('404', 'Homepage::notfound');
$routes->post('homepage/selectagent', 'Homepage::selectagent');
$routes->post('homepage/selectFromDataById', 'Homepage::selectFromDataById');
$routes->post('homepage/mailme', 'Homepage::mailme');
$routes->post('homepage/submitData', 'Homepage::submitData');
$routes->match(['GET', 'POST'], 'login', 'Login::index');
$routes->match(['GET', 'POST'], 'login/index', 'Login::index');
$routes->match(['GET', 'POST'], 'login/signUp', 'Login::signUp');
$routes->get('login/activate/(:segment)', 'Login::activate/$1');
$routes->match(['GET', 'POST'], 'login/reset', 'Login::reset');
$routes->get('login/logout', 'Login::logout');
$routes->get('enduser/logout', 'Login::logout');
$routes->get('oauth/google', 'Oauth::google');
$routes->get('oauth/facebook', 'Oauth::facebook');
$routes->get('oauth/google/callback', 'Oauth::google_callback');
$routes->get('oauth/facebook/callback', 'Oauth::facebook_callback');
$routes->match(['GET', 'POST'], 'enduser', 'Enduser::index');
$routes->get('userbooking', 'Userbooking::index');
$routes->match(['GET', 'POST'], 'userbooking/paynow/(:num)', 'Userbooking::paynow/$1');
$routes->get('install', 'Install::index');
$routes->get('install/requirements', 'Install::requirements');
$routes->match(['GET', 'POST'], 'install/database', 'Install::database');
$routes->match(['GET', 'POST'], 'install/settings', 'Install::settings');
$routes->get('install/finish', 'Install::finish');
$routes->get('page/(:segment)', 'Page::index/$1');
$routes->get('blog', 'Blog::index');
$routes->get('blog/(:segment)', 'Blog::index/$1');
$routes->get('invoice/(:segment)', 'Invoice::index/$1');
$routes->get('admin', 'Admin::index', ['filter' => 'adminAuth']);
$routes->get('auth', 'Auth::index');
$routes->match(['GET', 'POST'], 'auth/login', 'Auth::login');
$routes->get('auth/logout', 'Auth::logout');
$routes->get('general', 'General::index', ['filter' => 'adminAuth']);
$routes->get('general/dashboard', 'General::dashboard', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'general/settings', 'General::settings', ['filter' => 'adminAuth']);
$routes->get('general/themes', 'General::themes', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'general/upload_theme', 'General::upload_theme', ['filter' => 'adminAuth']);
$routes->get('general/set_theme/(:segment)', 'General::set_theme/$1', ['filter' => 'adminAuth']);
$routes->get('general/purge_cache', 'General::purge_cache', ['filter' => 'adminAuth']);
$routes->get('service', 'Service::index', ['filter' => 'adminAuth']);
$routes->get('service/services', 'Service::services', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'service/addservice', 'Service::addservice', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'service/editservice/(:num)', 'Service::editservice/$1', ['filter' => 'adminAuth']);
$routes->get('service/deleteService/(:num)/(:segment)', 'Service::deleteService/$1/$2', ['filter' => 'adminAuth']);
$routes->get('agents', 'Agents::index', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'agents/addagent', 'Agents::addagent', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'agents/editagent/(:num)', 'Agents::editagent/$1', ['filter' => 'adminAuth']);
$routes->get('agents/deleteAgent/(:num)/(:segment)', 'Agents::deleteAgent/$1/$2', ['filter' => 'adminAuth']);
$routes->get('bookings', 'Bookings::index', ['filter' => 'adminAuth']);
$routes->get('bookings/deleteBookings/(:num)/(:segment)', 'Bookings::deleteBookings/$1/$2', ['filter' => 'adminAuth']);
$routes->get('bookings/bookingConfirm/(:num)/(:segment)', 'Bookings::bookingConfirm/$1/$2', ['filter' => 'adminAuth']);
$routes->get('bookings/bookingCancel/(:num)/(:segment)', 'Bookings::bookingCancel/$1/$2', ['filter' => 'adminAuth']);
$routes->get('bookings/bookingPay/(:num)/(:segment)', 'Bookings::bookingPay/$1/$2', ['filter' => 'adminAuth']);
$routes->get('clients', 'Clients::index', ['filter' => 'adminAuth']);
$routes->get('clients/clients', 'Clients::clients', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'clients/editclients/(:num)', 'Clients::editclients/$1', ['filter' => 'adminAuth']);
$routes->get('clients/deleteclient/(:num)/(:segment)', 'Clients::deleteclient/$1/$2', ['filter' => 'adminAuth']);
$routes->get('gallery', 'Gallery::index', ['filter' => 'adminAuth']);
$routes->get('gallery/listGallery', 'Gallery::listGallery', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'gallery/addImg', 'Gallery::addImg', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'gallery/editImg/(:num)', 'Gallery::editImg/$1', ['filter' => 'adminAuth']);
$routes->get('gallery/deleteImg/(:num)/(:segment)', 'Gallery::deleteImg/$1/$2', ['filter' => 'adminAuth']);
$routes->get('gallery/categories', 'Gallery::categories', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'gallery/catAdd', 'Gallery::catAdd', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'gallery/catEdit/(:num)', 'Gallery::catEdit/$1', ['filter' => 'adminAuth']);
$routes->get('gallery/catDelete/(:num)/(:segment)', 'Gallery::catDelete/$1/$2', ['filter' => 'adminAuth']);
$routes->get('allpayments', 'Allpayments::index', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'allpayments/stripe', 'Allpayments::stripe', ['filter' => 'adminAuth']);
$routes->get('contact', 'Contact::index', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'contact/contactDetails', 'Contact::contactDetails', ['filter' => 'adminAuth']);
$routes->get('layout', 'Layout::index', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/social_keys', 'Layout::social_keys', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/analytics', 'Layout::analytics', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/recaptcha', 'Layout::recaptcha', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/email', 'Layout::email', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/meta_tags', 'Layout::meta_tags', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/ads', 'Layout::ads', ['filter' => 'adminAuth']);
$routes->get('layout/pages', 'Layout::pages', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/edit_page/(:segment)', 'Layout::edit_page/$1', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/create_page', 'Layout::create_page', ['filter' => 'adminAuth']);
$routes->get('layout/delete_page/(:segment)', 'Layout::delete_page/$1', ['filter' => 'adminAuth']);
$routes->get('layout/delete_page/(:segment)/(:segment)', 'Layout::delete_page/$1/$2', ['filter' => 'adminAuth']);
$routes->post('layout/update_page_order', 'Layout::update_page_order', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'layout/comment_settings', 'Layout::comment_settings', ['filter' => 'adminAuth']);
$routes->get('adminblog', 'Adminblog::index', ['filter' => 'adminAuth']);
$routes->post('adminblog/blogStatus', 'Adminblog::blogStatus', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'adminblog/add_post', 'Adminblog::add_post', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'adminblog/edit_post/(:num)', 'Adminblog::edit_post/$1', ['filter' => 'adminAuth']);
$routes->get('adminblog/delete_post/(:num)/(:segment)', 'Adminblog::delete_post/$1/$2', ['filter' => 'adminAuth']);
$routes->match(['GET', 'POST'], 'account/me', 'Account::me', ['filter' => 'adminAuth']);
$routes->get('updates', 'Updates::index', ['filter' => 'adminAuth']);
$routes->get('updates/main', 'Updates::main', ['filter' => 'adminAuth']);
$routes->post('updates/ajax_extract_package', 'Updates::ajax_extract_package', ['filter' => 'adminAuth']);
$routes->post('updates/ajax_import_database', 'Updates::ajax_import_database', ['filter' => 'adminAuth']);
$routes->post('updates/ajax_finalize_settings', 'Updates::ajax_finalize_settings', ['filter' => 'adminAuth']);
